name: Spacegame.Web
on:
  push:
    branches:
      - master

jobs:
  BUILD_JOB:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
        
    #- name: Setup MSbuild
    #  uses: microsoft/setup-msbuild@v1
      
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet publish Tailspin.SpaceGame.Web.sln -c Release -o ${{github.workspace}}/stagingdir

    - name: Test
      run: dotnet test --configuration Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$GITHUB_WORKSPACE/TestResults/Coverage/      
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: space-web
        path: ${{github.workspace}}
