name: Test

on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: [self-hosted,runner1]

    steps:
    - uses: actions/checkout@v2
    - name: Test
      shell: powershell
      run: Write-Host "Executing on 1"
  deploy:
    needs: build
    runs-on: [self-hosted,runner2]

    steps:
    - uses: actions/checkout@v2
    - name: Test
      shell: powershell
      run: Write-Host "Executing on 2"
