name: Test

on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: [self-hosted,psr-agent]

    steps:
    - uses: actions/checkout@v2
    - name: Test
      shell: powershell
      run: Write-Host "Hello
