name: Spacegame.Web.k8s
on:
  push:
    branches: [master, k8s]
  pull_request:
    branches: [ master ]

jobs:
  CONTAINER_BUILD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - uses: azure/docker-login@v1
      with:
        login-server: darquewarrior.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Install Trivy
      run: |
        #!/bin/bash
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy
        echo $HOME/Library/Caches
    
    - name: build, scan and tag image
      run: |
        docker build -f $GITHUB_WORKSPACE/Tailspin.SpaceGame.Web/Dockerfile -t ${{ secrets.ACR }}/tailspinspacegameweb:${{ github.run_number }} .
        trivy --exit-code 0 --severity MEDIUM,HIGH ${{ secrets.ACR }}/tailspinspacegameweb:${{ github.run_number }}
    
    - name: push image
      run: |
        docker push ${{ secrets.ACR }}/tailspinspacegameweb:${{ github.run_number }}	
#===============================================================================================================
  AKS-DEPLOY:
    runs-on: ubuntu-latest
    needs: CONTAINER_BUILD
    steps:
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}    
    
    - uses: azure/docker-login@v1
      with:
        login-server: darquewarrior.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
      
    - uses: azure/setup-helm@v1
      with:
        version: 'latest'
        id: install 

    - name: 'Helm Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'spacegameweb'
        namespace: 'default'
        chart: 'app'
        token: '${{ github.token }}'
        values: |
          name: spacegameweb
      env:
        KUBECONFIG_FILE: '${{ secrets.AKS }}'
		
    - name: Azure logout
      run: |
        az logout
